import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/UI/Navbar";
import Footer from "@/components/UI/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "St. Bartholomeus — Schuttersgilde",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col items-center dark pb-5`}>
        <section className="flex flex-col w-9/12 max-xl:w-11/12">
          <Navbar />
          {children}
          <Footer />
        </section>
      </body>
    </html>
  );
}
